
version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres_net

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./.env.dev
    networks:
      - postgres_net
    restart: always
    entrypoint: ["bash", "./docker-entrypoint.sh"]
         

  
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U usman -d usman"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    
    
  
volumes:
  postgres_data:

networks:
  postgres_net:
    driver: bridge